services:
  task-manager-db:
    image: postgres:15.3
    container_name: task-manager-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=luis
      - POSTGRES_PASSWORD=test1234
    volumes:
      - ./postgres:/var/lib/postgresql/data
